### ISSUE TITLE
[SOLVED] module 'steam' error

### ISSUE THREAD

**Issue by emdy** [steam-forward/node-steam-forum#132]
where is steam dir because when i run bot node show var Steam = require('steam'); error
![er](https://cloud.githubusercontent.com/assets/16139265/11572291/7da23856-9a11-11e5-934e-e8e58aa5e1dd.png)

**Comment by scholtzm** [comment]
You need to `npm install` it.

**Comment by emdy** [comment]
npm install on steam-tradeoffers dir?

**Comment by Alex7Kom** [comment]
Your initial description of the problem was more correct:

![image](https://cloud.githubusercontent.com/assets/181961/11573074/64e5dc42-9a15-11e5-8f40-1ac570610d71.png)

Looks like a bug with npm, see https://github.com/seishun/node-steam/issues/281 and https://github.com/npm/npm/issues/9633 for solutions.

**Comment by emdy** [comment]
Reinstall and work now!
![1](https://cloud.githubusercontent.com/assets/16139265/11573690/b0eccfc6-9a18-11e5-8185-316876274422.png)

**Comment by waza123x** [comment]
I uninstalled node and downloaded it again recommended version, and all works fine now.
