### ISSUE TITLE
steam-tradeoffers .getItems(): Error: No session

### ISSUE THREAD

**Issue by AardvarkMike** [steam-forward/node-steam-forum#2]
I'm trying to use .getItems() to verify I've actually received some items I'm expecting. 

I'm using it in the following fashion;

```javascript
offers.acceptOffer({tradeOfferId: offer.tradeofferid});  
console.log('Checking items');
offers.getItems({
  tradeId: offer.tradeid,
}, function(error, data) {
  if (!error) {
    console.log(data);
  } else {
    console.log(error);
  }
});
```

The offer is accepted fine, but .getItems() returns "[Error: No session]"

I'm fairly sure the session is set ok (see code below) as tradeoffers are accepted/sent just fine. 

```javascript
bot.on('webSessionID', function(sessionId) {
    session_id = sessionId;
    bot.webLogOn(function(cookies) {
      session_cookies = cookies;
      offers.setup({ sessionID: sessionId, webCookie: cookies });
    });
  });
```

Any suggestions?

**Comment by scholtzm** [comment]
You should call `getItems` in your callback. Everything is async, remember?

**Comment by Alex7Kom** [comment]
First, you assume that `offer` object always contains `tradeid` which is false, because it does contain it only when trade for which it requested was successful. In your case `offer.tradeid` is `undefined`.

Second, even if somehow `offer` did contain valid `tradeid` property, you won't get the list of items when you do `.getItems()` because trade is not completed yet. Please, do not forget that all I/O in Node.js is async unless stated otherwise.

**Comment by AardvarkMike** [comment]
It seems so obvious now you've pointed it out. I feel like a total idiot. 

I'll show myself out :-1:

**Comment by AardvarkMike** [comment]
For anyone else facing the same issue, I figured I'd post my solution, because it was not obvious. 

The docs say that the tradeid can be had from an offer, whereas I found it was only received in the response from accepting the offer - something the docs suggest doesn't have anything meaning in it. 

```javascript
offers.acceptOffer({
    tradeOfferId: offer.tradeofferid
}, function(error, traderesponse) {
    if ('undefined' != typeof traderesponse.tradeid) {
        offers.getItems({
            tradeId: traderesponse.tradeid,
        }, function(error, tradedata) {
            if (!error) {
                console.log(tradedata);
            }
        });
    }
});
```

**Comment by Alex7Kom** [comment]
The offer does contain `tradeid` but after the trade is done, which means you need to request the offer through `.getOffer()` again after that. About `.acceptOffer`, it does contain this property at this moment, but it may unpredictably change in the future so the docs do not feature it. (It is not like Valve does not change Web API, but API breaks less often).
Please close the issue if your problem is resolved.

**Comment by scholtzm** [comment]
btw. @AardvarkMike your solution won't work for very large trade offers.

**Comment by AardvarkMike** [comment]
@scholtzm Ok, care to share why? :)

**Comment by scholtzm** [comment]
Large trade offers always fail. Test it with 150 items and you will see. The offer will be eventually accepted though.

**Comment by AardvarkMike** [comment]
@scholtzm I assume this is the error where quite often when trying to accept large, you end up with an error, but a few seconds/minutes later the trade gets accepted anyway?

I did a little test and got a couple of 500 errors before finally getting a response.
