### ISSUE TITLE
There was an error accepting this trade offer. Please try again later. (24)

### ISSUE THREAD

**Issue by balatsky** [steam-forward/node-steam-forum#3]
I can't accept offer because of "There was an error accepting this trade offer. Please try again later. (24)". It wasn't before.

**Comment by BenWoodford** [comment]
Haven't run into 24 personally, but look at the HTTP Code: 403. It's pretty safe to assume it's permission related. 24 seems to be a bit of an obscure one (I feel your pain, I'm getting 8).

Make sure the account isn't limited (buy a game on it or redeem a gift on it), make sure your offer ID is correct and make sure the account isn't trade-banned because it's too new/on a new device. Can't remember the respective IDs (and really wish Steam would give text instead of numbers) so some of these may not apply, but always good to check

**Comment by scholtzm** [comment]
Possibly SteamGuard kicking in.
