### ISSUE TITLE
Steam randomly 'loses' offers?

### ISSUE THREAD

**Issue by BenWoodford** [steam-forward/node-steam-forum#50]
This isn't strictly a node issue, but this is the best place to get resolutions I find so here goes.

Is anyone else finding Steam will sometimes just outright "lose" offers? I've had offers made with makeOffer, the trade go through but a mere minute later (and this was a minute, trade entry was made at 8:58 and updated at 8:59 to mark it as failed in my DB) the trade will be "lost in the tubes" as I have it put down. i.e. it can't be found in getOffers() or getOffer() by the offer ID

The offer ID, in case anyone spots something odd about it being too short, too long, whatever, is 599352643. Not like much can be done with it seeing as I can't even find it using the account that made it.

Anyone have any thoughts?

**Comment by dragonbanshee** [comment]
I know this is late, but I've had this happen to me before. I trade my bot, the bot says that it accepts, but in my sent offers says items unavailable. The items that I traded are neither in my inventory or the bots inventory, and I cannot find the offer in my offer history. It usually shows up a few hours later, but it's still weird when it happens and I don't know a fix for it.

**Comment by BenWoodford** [comment]
Does the item show up back in the sender's inventory? Could be related to when CS:GO Player Inventories are "Delayed": https://steamstat.us/ which seems to cause problems.

node-inventoryhistory is being a lifesaver, as that's generally as accurate as possible if you can manage to match up your trades (thanks so much for not putting the offer ID there Steam, real helpful)

**Comment by scholtzm** [comment]
@BenWoodford @dragonbanshee 

Little bit late to the party but something @MatthewLilley and I have been testing today.

There were 2 test scenarios involving 2 separate clients - "sender" and "receiver". Each scenario was tested several times.

**1st scenario:**
* sender sends 5 trade offers to receiver with 1500ms gap between each request
* receiver logs these offers using node-steam's `tradeOffers` event

*Result:*
* all 5 trade offers logged by the receiver, no problem

**2nd scenario:**
* sender sends 5 trade offers to receiver with 1500ms gap between each request
* receiver logs these offers using node-steam's `tradeOffers` event
* in addition, receiver declines the trade offers asap

*Result:*
* `tradeOffers` event fires only couple times, but usually not for all 5 offers
  * this is most likely caused by the fact that at the same time we are also declining trade offers and Steam is simply dumb and +1 and -1 is simply too confusing... :grinning: 
* however the bigger problem:
  * sender prints 5 unique `tradeofferid`s to console
  * receiver receives only 4 (usually) trade offers -> the 5th one got lost in the limbo and it's not even displaying on the website (!!!)
  * sending another trade offer yields 2 offers -> the one we just sent and the one that was stuck in the limbo
* after pinpointing this behaviour, I was able to replicate it almost every single time

**Conclusion:**
Accepting/declining trade offer while receiving another seems to kill the trade offer notification as well as the incoming trade offer in certain cases.

Possibly a timing issue/race condition on their end. If anyone wants to test it out, the scripts are here: https://gist.github.com/scholtzm/8af1cc037caede283a1c

**Comment by BenWoodford** [comment]
I've started using [node-steam-inventoryhistory](https://github.com/DoctorMcKay/node-steam-inventoryhistory) which so far has been a life saver, with the exception of Steam's random 'span-not-anchor' trades which may or may not have processed.

**Comment by andrewda** [comment]
@BenWoodford [node-steam-inventoryhistory](https://github.com/DoctorMcKay/node-steam-inventoryhistory) is now deprecated and all of its functionality has been moved to [node-steamcommunity](https://github.com/DoctorMcKay/node-steamcommunity/blob/master/components/inventoryhistory.js).
