### ISSUE TITLE
Is the acceptOffer() callback response reliable for finding an offers tradeid?

### ISSUE THREAD

**Issue by StevePavlin** [steam-forward/node-steam-forum#65]
I noticed that the acceptOffer() response contains the tradeid of the accepted offer, something that I would normally get by using getOffer() method with the tradeofferid. Is it reliable to use this response for the tradeid? Or should I be using getOffer() following the accept?

**Comment by dragonbanshee** [comment]
I don't think the response from acceptOffer gives you a trade Id, but you pass the offerid as an argument for accept offer. You get the trade offer Id via offer.tradeOfferId.

**Comment by Alex7Kom** [comment]
It does return `tradeid`(because Steam returns it), but it is not documented exactly because I don't consider reliable anything that Steam returns in such methods. `tradeofferid` in `makeOffer()` is documented purely by accident. In fact, I don't even think that 'reliable' is applicable to anything Valve creates.

**Comment by dragonbanshee** [comment]
Oh, that's weird. I usually log the response from make/accept/decline, but it's usually just blank unless there's an error.
