### ISSUE TITLE
Get items names without accepting trade offer and using getItems()

### ISSUE THREAD

**Issue by mich356c** [steam-forward/node-steam-forum#81]
Hey errone,

I'm wondering if it's possible to get the item names before accepting the trade? I want to do a price check before accepting/declining, and my current method is quite slow, but to look up the prices I need the market_hash_name, and (afaik) all the IDs are useless for that :/

Atm I'm simply calling http://api.steampowered.com/ISteamEconomy/GetAssetClassInfo with all the class IDs from the trade, to get the market_hash_name's then checking with my own database to get the prices. It's slow. Really slow.

Edit: Would I have to accept it, use getItems(), get the value, and then send it back if it's too low? Seems stupid

Thank you :)

**Comment by scholtzm** [comment]
Since trade offer contains only IDs, there are 2 options:

1. Load inventory for each participant and get the names from there.
2. `GetTradeOffers` (and probably `GetTradeOffer`) accepts `get_descriptions` option.

https://github.com/Alex7Kom/node-steam-tradeoffers#getoffersoptions-callback
https://developer.valvesoftware.com/wiki/Steam_Web_API/IEconService

**Comment by mich356c** [comment]
Oh my god I can't believe I didn't notice that `get_descriptions` option... Thank you so much! :D
